### ISSUE TITLE
Podcasts don't update on podcast services like itunes

### ISSUE THREAD

**Issue by kayte8** [indianapublicmedia/indianapublicmedia-web#26]
Earth Eats podcasts have not updated to podcast services like itunes and stitcher since March 9. Listeners who access the show through the podcast apps don't have access to the show.

**Comment by eobanb** [comment]
Just checked Earth Eats on iTunes and it appears to be working fine (three new episodes since March 9):

https://itunes.apple.com/us/podcast/podcasts-earth-eats/id256713181?mt=2

Occasionally podcast clients will automatically pause downloads of a given podcast if the feed is unavailable for a certain amount of time; however it is up to individual users to resume downloads—nothing we have control over.

**Comment by kayte8** [comment]
?Okay, I am sorry about that. It is not updating on my phone, but Mark just checked and it is fine on his, so it must be an issue with my settings or something like that. Apologies for troubling you with that.


Kayte Young
Producer of Earth Eats<http://indianapublicmedia.org/eartheats/>
<http://indianapublicmedia.org/eartheats/>
Multimedia Producer-WFIU
Indiana University
Bloomington, Indiana
younka@iu.edu

________________________________
